services:
  - type: web
    name: soil-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT
    plan: free
